<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/AdForLinux.DirectoryServices/AdForLinux.DirectoryServices.csproj" />
  </ItemGroup>
</Project>
